### ISSUE TITLE
'NoneType' object has no attribute 'set_cookie'

### ISSUE THREAD

**Issue by wangkwok** [nnja/tweeter#6]
Hi, Could you possibly help me to solve the problem when I start the server, thank you very much! 
AttributeError at /

'NoneType' object has no attribute 'set_cookie'

Request Method:     GET
Request URL:    http://localhost:8000/
Django Version:     1.9
Exception Type:     AttributeError
Exception Value:    

'NoneType' object has no attribute 'set_cookie'

Exception Location:     C:\Users\dlwkwok\Envs\tweeter\lib\site-packages\django\middleware\csrf.py in process_response, line 229
Python Executable:  C:\Users\dlwkwok\Envs\tweeter\Scripts\python.exe
Python Version:     3.5.1
Python Path:    

['C:\tweeter',
 'C:\Users\dlwkwok\Envs\tweeter\Scripts\python35.zip',
 'C:\Users\dlwkwok\Envs\tweeter\DLLs',
 'C:\Users\dlwkwok\Envs\tweeter\lib',
 'C:\Users\dlwkwok\Envs\tweeter\Scripts',
 'c:\users\dlwkwok\appdata\local\programs\python\python35\Lib',
 'c:\users\dlwkwok\appdata\local\programs\python\python35\DLLs',
 'C:\Users\dlwkwok\Envs\tweeter',
 'C:\Users\dlwkwok\Envs\tweeter\lib\site-packages']

Server time:    Wed, 16 Dec 2015 16:46:46 +0800

**Comment by wangkwok** [comment]
anyone can help me, thank you very much!

**Comment by CoolestNerdIII** [comment]
If you look at the views.py in the index method, nothing is being returned if the user is not logged in. There are two optional workarounds for this:

1. You are using django==1.9. If you use virtualenv and download django from the requirements file, it will work as intended.

2. Handle the case for if the user is None by adding an else statement. To get it to run properly, try adding this: 
```
else:
        return render(request, 'tweeter/index.html’)
```
